import { Agency } from "../entities/agency";

export const AGENCY_DATA: Agency[] = [
    {
        id: 1,
        fullName: 'Nguyen A',
        address: 'CT',
        birthday: null,
        phone: '0698546321',
        note: '',
        accountName: '',
        password: '',
    },
    {
        id: 2,
        fullName: 'Tran Van Ti',
        address: 'HG',
        birthday: null,
        phone: '0685676321',
        note: '',
        accountName: '',
        password: '',
    },
    {
        id: 3,
        fullName: 'Ly Dong',
        address: 'AG',
        birthday: null,
        phone: '06985469877',
        note: '',
        accountName: '',
        password: '',
    },
    {
        id: 4,
        fullName: 'Nguyen Van',
        address: 'HCM',
        birthday: null,
        phone: '0698226320',
        note: '',
        accountName: '',
        password: '',
    },
    {
        id: 5,
        fullName: 'Nguyen Hao',
        address: 'LA',
        birthday: null,
        phone: '0998546331',
        note: '',
        accountName: '',
        password: '',
    },
    {
        id: 6,
        fullName: 'Dai Ly Nam Ky',
        address: 'HCM',
        birthday: null,
        phone: '0927546691',
        note: '',
        accountName: 'namky@gmail.com',
        password: '12345678',
    },
];